// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YORMUNGAND.Data;

namespace YORMUNGAND.Migrations.eCESSDBContentMigrations
{
    [DbContext(typeof(eCESSDBContent))]
    [Migration("20210426135707_d492")]
    partial class d492
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YORMUNGAND.Data.Models.VIRCommentAnalitics", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AUTHOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ENABLE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("END_TIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("SQL_STRING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("START_TIME")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("CESSVIRCOMMENTS");
                });
#pragma warning restore 612, 618
        }
    }
}
