// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YORMUNGAND.Data;

namespace YORMUNGAND.Migrations.CESSDBContentMigrations
{
    [DbContext(typeof(CESSDBContent))]
    partial class CESSDBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YORMUNGAND.Data.Models.MainReportWave1", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ключ (счетчик)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BD_COM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("БД_комментарий");

                    b.Property<string>("CONTRACT_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Контракт_номер");

                    b.Property<string>("DIADOK_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Диадок_ID");

                    b.Property<string>("DIADOK_LINK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Диадок_ссылка");

                    b.Property<string>("DIADOK_SIGN_DATE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Диадок_Дата_подписания");

                    b.Property<string>("DIADOK_UPLOAD_DATE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Диадок_Дата_загрузки");

                    b.Property<string>("DOG_DATE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Договор_дата");

                    b.Property<string>("DOG_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Договор_номер");

                    b.Property<string>("DOUBLE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Дубль");

                    b.Property<string>("DS_DATE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ДС_Дата");

                    b.Property<string>("DS_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ДС_Номер");

                    b.Property<string>("ECM_FILL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Дозаполнение_ЕСМ");

                    b.Property<string>("ECM_LINK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ЕСМ_ссылка");

                    b.Property<string>("ERROR1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ошибка1");

                    b.Property<string>("ERROR2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ошибка2");

                    b.Property<string>("FILIAL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Филиал");

                    b.Property<string>("GEO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("География");

                    b.Property<string>("GFK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ГФК");

                    b.Property<string>("IMS_LINK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMS_ссылка");

                    b.Property<string>("INITIATOR_FIO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Инициатор_ФИО");

                    b.Property<string>("INITIATOR_MAIL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Инициатор_почта");

                    b.Property<string>("NRI_BS_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NRI_БС_Номер");

                    b.Property<string>("NRI_BS_NAME")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NRI_БС_Наименование");

                    b.Property<string>("NRI_CODE_PROJECT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NRI_Код_проекта");

                    b.Property<string>("NRI_LINK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NRI_ссылка");

                    b.Property<string>("PROCESSING")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Обработка");

                    b.Property<string>("PROSTAVLENIE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Проставление");

                    b.Property<string>("PROVIDER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Поставщик");

                    b.Property<string>("PROVIDER_INN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Поставщик_ИНН");

                    b.Property<string>("PR_COM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PR_Комментарий");

                    b.Property<string>("PR_FILE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PR_файл");

                    b.Property<string>("PR_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PR_Номер");

                    b.Property<string>("PR_STATUS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PR_статус");

                    b.Property<string>("REGION")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Регион");

                    b.Property<string>("RESPONSIBLE_FIO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ответственный_ФИО");

                    b.Property<string>("SEVD")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("СЭВД");

                    b.Property<string>("SEVD_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("СЭВД_Номер");

                    b.Property<string>("STAGE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Этап");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Статус");

                    b.Property<string>("TECH_ERROR")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Тех_Ошибка");

                    b.Property<string>("VIR_COM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_комментарий");

                    b.Property<DateTime>("VIR_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("ВИР_дата");

                    b.Property<string>("VIR_DIAP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Диапазоны");

                    b.Property<string>("VIR_DOC_TYPE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Тип_документа");

                    b.Property<string>("VIR_DOP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Дополнение");

                    b.Property<string>("VIR_DOP_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Дополнение_номер");

                    b.Property<string>("VIR_END_WORK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Завершение_работ");

                    b.Property<string>("VIR_INTEGRATION_DATE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Дата_интеграции");

                    b.Property<string>("VIR_PAY_CONDITIONS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Условия_платежа");

                    b.Property<string>("VIR_START_WORK")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ВИР_Начало_работ");

                    b.Property<decimal>("VIR_SUMM_WO_NDS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ВИР_Сумма_без_НДС");

                    b.Property<string>("ZM_LOT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ЗМ_с_лотом");

                    b.Property<string>("ZP_N")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ЗП_Номер");

                    b.Property<string>("ZP_STATUS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ЗП_Статус");

                    b.HasKey("id");

                    b.ToTable("MAIN-1");
                });

            modelBuilder.Entity("YORMUNGAND.Data.Models.StatistikCessReportDwnld", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EVENT_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("ROWS_COUNT")
                        .HasColumnType("int");

                    b.Property<string>("USER")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StatCessReportDwnld");
                });

            modelBuilder.Entity("YORMUNGAND.Data.Models.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TEST");
                });
#pragma warning restore 612, 618
        }
    }
}
